spring:
  datasource:
    username: thesis
    password: thesis
    url: jdbc:postgresql://localhost:5432/account-service

  jpa:
    show-sql: true
    properties: 
        default_schema: thesis
        hibernate.hbm2ddl.auto: create-drop
        
logging:
  level:
    org:
      hibernate:
        sql:  debug