
server:
   port: 4040
   
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000

ribbon:
  eureka:
    enabled: true

##########  Zuul Configuraiton ##########    
zuul:
  ignoredServices: '*'
  routes:
    account-service:
        path: /accounts/**
        serviceId: account-service

    project-service:
        path: /projects/**
        serviceId: project-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
        
management:
  security:
    enabled: false
    